import type { CaseRecord } from "./cases-data";

type HistoricalCaseInput = {
  id: string;
  date: string;
  title: string;
  targets: string;
  institution: CaseRecord["institution"];
  institutionType: string;
  description: string;
  itemIds: number[];
  laws: string;
  source: string;
};

const topicByItem: Record<number, string> = {
  1: "개인정보 보호책임자",
  2: "내부 관리계획",
  3: "수탁자 관리·감독",
  4: "소프트웨어 관리",
  5: "개인정보보호 교육",
  6: "접근통제",
  7: "접근통제",
  8: "모니터링",
  9: "악성프로그램",
  10: "접속기록",
  11: "보안패치",
  12: "접근통제",
  13: "접근통제",
  14: "접속기록",
  15: "모니터링",
  16: "접근통제",
  17: "접근권한",
  18: "접근권한",
  19: "인증",
  20: "인증",
  21: "물리적 통제",
  22: "이동식 저장매체",
  23: "보안패치",
  24: "파기",
  25: "웹 보안",
  26: "보안패치",
};

const learningByItem: Record<number, string> = {
  1: "개인정보 보호책임자의 권한과 점검 책임을 실질적으로 보장하세요.",
  2: "내부 관리계획과 침해사고 대응절차를 수립하고 이행 여부를 점검하세요.",
  3: "수탁자와 외주인력의 개인정보 보호조치 이행 여부를 정기적으로 감독하세요.",
  4: "DB 접속 단말의 비인가 소프트웨어 사용을 통제하세요.",
  5: "DB 접근 가능자를 대상으로 정기적인 개인정보보호 교육을 실시하세요.",
  6: "개인정보처리시스템의 접속 가능 IP와 외부 접근을 제한하세요.",
  7: "업무에 불필요한 서비스 포트를 차단하세요.",
  8: "침입차단·탐지 정책을 적용하고 보안경보를 지속적으로 점검하세요.",
  9: "악성프로그램 탐지·치료 체계와 최신 보안프로그램을 운영하세요.",
  10: "네트워크 접속로그를 기록·분석하고 안전하게 보관하세요.",
  11: "네트워크·정보보호 장비의 보안패치를 적시에 적용하세요.",
  12: "네트워크를 통한 비인가 DB 접근을 차단하세요.",
  13: "DB 서버의 불필요한 서비스 포트를 차단하세요.",
  14: "개인정보취급자와 DB 접속자의 접속기록을 빠짐없이 남기세요.",
  15: "접속기록과 개인정보 다운로드 내역을 정기적으로 점검하세요.",
  16: "DB 관리자 단말을 인터넷 접속망과 분리하세요.",
  17: "업무에 필요한 최소한의 접근권한만 차등 부여하세요.",
  18: "업무변경·퇴직 시 접근권한을 지체 없이 변경하거나 말소하세요.",
  19: "개인정보처리시스템과 관리자 접속에 안전한 인증수단을 적용하세요.",
  20: "반복 인증 실패 시 계정 잠금 또는 접근제한을 적용하세요.",
  21: "서버실 등 물리적 보호구역의 출입을 인가된 사람으로 제한하세요.",
  22: "USB 등 이동식 저장매체는 관리자 승인 후 사용하도록 통제하세요.",
  23: "개인정보취급자 단말과 서버 운영체제의 보안패치를 적시에 적용하세요.",
  24: "저장매체 불용처리 시 개인정보를 복구할 수 없도록 파기하세요.",
  25: "SQL 삽입·파일 업로드 등 주요 웹 취약점을 정기적으로 진단·보완하세요.",
  26: "웹서버 프로그램과 운영체제의 보안패치를 적시에 적용하세요.",
};

const dispositionLabels = [
  "과징금",
  "과태료",
  "시정명령",
  "시정권고",
  "개선권고",
  "징계권고",
  "공표명령",
] as const;

const historicalCaseInputs: HistoricalCaseInput[] = [
  {
    id: "historic-2020-01",
    date: "2020-12-09",
    title: "통신사·대리점 개인정보 처리 위탁 관리 소홀",
    targets: "통신사·대리점 개인정보 처리 위탁 관리 소홀",
    institution: "민간기업",
    institutionType: "민간·통신",
    description: "통신사가 대리점에 위탁한 개인정보에 대한 관리·감독 및 대리점의 안전조치 소홀. 과태료·시정조치",
    itemIds: [3],
    laws: "보호법 제26·29조(당시 기준)",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552399",
  },
  {
    id: "historic-2021-01",
    date: "2021-01-27",
    title: "개인정보 관리수준 미흡 30개 지방자치단체",
    targets: "개인정보 관리수준 미흡 30개 지방자치단체",
    institution: "공공기관",
    institutionType: "지자체",
    description: "관리수준 진단 후 직권조사. 시스템 접속기록 누락, 계정 공유 등 47건. 시정권고, 10개 기관 징계권고",
    itemIds: [14,19],
    laws: "보호법 제29조, 당시 안전성 확보조치 기준",
    source: "https://www.korea.kr/news/policyNewsView.do?newsId=156434027",
  },
  {
    id: "historic-2021-02",
    date: "2021-01-27",
    title: "네이처리퍼블릭·에스디생명공학 등 4개 사업자",
    targets: "네이처리퍼블릭·에스디생명공학 등 4개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "해킹·유출신고로 조사. SQL 주입·웹셸 등 웹 취약점과 보호조치 소홀. 과징금·과태료·시정명령",
    itemIds: [8,25],
    laws: "구 정보통신망법 제28조 등",
    source: "https://www.korea.kr/news/policyNewsView.do?newsId=156434027",
  },
  {
    id: "historic-2021-03",
    date: "2021-05-26",
    title: "쿠팡·네이버 등 7개 열린장터",
    targets: "쿠팡·네이버 등 7개 열린장터",
    institution: "민간기업",
    institutionType: "민간·플랫폼",
    description: "판매자 개인정보 처리 위탁·안전관리 실태조사. 수탁자 관리·감독 및 안전관리 미흡. 총 5,220만 원 과태료·시정명령",
    itemIds: [3],
    laws: "보호법 제26·29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552455",
  },
  {
    id: "historic-2021-04",
    date: "2021-09-08",
    title: "개인정보 보호조치 위반 19개 공공기관",
    targets: "개인정보 보호조치 위반 19개 공공기관",
    institution: "공공기관",
    institutionType: "공공",
    description: "국정감사·웹 보안 취약 지적 후 조사. 접속기록 누락, 추가인증 미적용, 계정 공유, 비밀번호 비암호화 전송. 과태료 9,360만 원 등",
    itemIds: [14,19],
    laws: "보호법 제29조, 당시 안전성 확보조치 기준",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552497",
  },
  {
    id: "historic-2021-05",
    date: "2021-09-08",
    title: "캐논코리아비즈니스솔루션·랜트·이스트젠·유킹 등 6개 사업자",
    targets: "캐논코리아비즈니스솔루션·랜트·이스트젠·유킹 등 6개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "설문 결과 공개 설정, 홈페이지 취약점 방치·웹셸 업로드, 개발 오류로 유출. 과태료 4,800만 원·시정명령",
    itemIds: [8,25,26],
    laws: "구 정보통신망법 제28조·보호법 제29조",
    source: "https://www.korea.kr/news/policyNewsView.do?newsId=156470074",
  },
  {
    id: "historic-2021-06",
    date: "2021-10-27",
    title: "바노바기·리뉴미 등 의료분야 12개 사업자",
    targets: "바노바기·리뉴미 등 의료분야 12개 사업자",
    institution: "민간기업",
    institutionType: "의료",
    description: "랜섬웨어·해킹·다크웹 유출, 계정 공유, 인증 취약, 접속기록 누락. 과징금·과태료·시정조치",
    itemIds: [8,14,19,25,26],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552517",
  },
  {
    id: "historic-2021-07",
    date: "2021-11-10",
    title: "개인정보보호 법규 위반 7개 사업자",
    targets: "개인정보보호 법규 위반 7개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "유출신고 등에 따른 조사. 접근통제·접속기록·인증·웹 보안 미흡. 총 4,560만 원 과태료·시정명령",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552524",
  },
  {
    id: "historic-2021-08",
    date: "2021-12-08",
    title: "청주시 자원봉사센터 등 안전조치 미흡 8개 사업자·기관",
    targets: "청주시 자원봉사센터 등 안전조치 미흡 8개 사업자·기관",
    institution: "공공기관",
    institutionType: "공공·민간",
    description: "안전조치 미흡으로 개인정보 유출. 총 3,320만 원 과태료·공표 등",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552536",
  },
  {
    id: "historic-2022-01",
    date: "2022-01-26",
    title: "플라이팝콘·피씨유·알럽스킨",
    targets: "플라이팝콘·피씨유·알럽스킨",
    institution: "민간기업",
    institutionType: "민간·쇼핑",
    description: "유출신고. 관리자 안전인증·IP 제한·취약점 점검·접속기록 미흡. 과태료 2,680만 원·시정명령",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552554",
  },
  {
    id: "historic-2022-02",
    date: "2022-02-23",
    title: "트리플콤마(골드스푼)",
    targets: "트리플콤마(골드스푼)",
    institution: "민간기업",
    institutionType: "민간·앱",
    description: "해킹 유출. 관리자 접근 IP 미제한 등 보호조치 소홀. 과징금 1억 2,979만 원·과태료 1,860만 원",
    itemIds: [6],
    laws: "보호법 제29조 등",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552570",
  },
  {
    id: "historic-2022-03",
    date: "2022-03-23",
    title: "개인정보 유출 16개 사업자",
    targets: "개인정보 유출 16개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "해킹·업무상 실수로 유출. 접근통제·접속기록·인증·웹 취약점 등 안전조치 소홀. 과징금·과태료·시정조치",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552574",
  },
  {
    id: "historic-2022-04",
    date: "2022-04-13",
    title: "개인정보보호 법규 위반 6개 사업자",
    targets: "개인정보보호 법규 위반 6개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "유출·신고에 따른 조사. 접근통제·접속기록·인증·웹 보호조치 미흡. 과태료·시정조치",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552582",
  },
  {
    id: "historic-2022-05",
    date: "2022-05-11",
    title: "지티지엔터프라이즈·예스콜닷컴·아디다스·리얼마케팅·트렌비",
    targets: "지티지엔터프라이즈·예스콜닷컴·아디다스·리얼마케팅·트렌비",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전인증·IP 제한·침입탐지·유해파일·접속기록 점검·보안서버 미흡. 과징금 2,933만 원·과태료 3,240만 원",
    itemIds: [6,8,9,14,15,19,25],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552594",
  },
  {
    id: "historic-2022-06",
    date: "2022-05-25",
    title: "계원예술대 등 8개 기관",
    targets: "계원예술대 등 8개 기관",
    institution: "공공기관",
    institutionType: "공공·교육",
    description: "해킹·업무과실. 웹셸·SQL 주입, 접속·인증 등 안전조치 미흡. 과태료 4,050만 원·시정권고",
    itemIds: [8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552599",
  },
  {
    id: "historic-2022-07",
    date: "2022-06-08",
    title: "위더스교육·뉴지스탁·창비",
    targets: "위더스교육·뉴지스탁·창비",
    institution: "민간기업",
    institutionType: "민간",
    description: "웹셸·SQL 주입, 파일 업로드 검증 및 침입탐지·차단 운영 소홀. 과징금 3,700만 원·과태료 2,140만 원",
    itemIds: [8,25,26],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552603",
  },
  {
    id: "historic-2022-08",
    date: "2022-06-22",
    title: "수원시·국토교통부 대규모 행정시스템",
    targets: "수원시·국토교통부 대규모 행정시스템",
    institution: "공공기관",
    institutionType: "지자체·중앙기관",
    description: "공무원의 흥신소 유출 사건. 접근권한·권한회수·접속기록 점검 등 관리 미흡. 수원시 과태료·시정조치, 국토부 개선권고",
    itemIds: [14,15,17,18,19],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552607",
  },
  {
    id: "historic-2022-09",
    date: "2022-07-13",
    title: "브랜디·에스테크엘이디",
    targets: "브랜디·에스테크엘이디",
    institution: "민간기업",
    institutionType: "민간·쇼핑",
    description: "AWS 접근키·관리자 계정 악용, IP 제한 미적용 등. 과징금 3억 8,900만 원·과태료 1,380만 원",
    itemIds: [6,17,19],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552619",
  },
  {
    id: "historic-2022-10",
    date: "2022-08-10",
    title: "국민대·한국조폐공사 등 7개 공공기관",
    targets: "국민대·한국조폐공사 등 7개 공공기관",
    institution: "공공기관",
    institutionType: "공공·교육",
    description: "DB 이관·설정 변경 오류, 유출·침해신고. DB 접근·기록·권한 관리 미흡. 과태료 2,160만 원·시정권고",
    itemIds: [12,14,17],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552631",
  },
  {
    id: "historic-2022-11",
    date: "2022-08-10",
    title: "발란",
    targets: "발란",
    institution: "민간기업",
    institutionType: "민간·쇼핑",
    description: "해킹으로 고객정보 유출, 안전조치 의무 위반. 과징금 5억 1,259만 원·과태료 1,440만 원",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552633",
  },
  {
    id: "historic-2022-12",
    date: "2022-09-14",
    title: "개인정보보호 법규 위반 16개 지방자치단체",
    targets: "개인정보보호 법규 위반 16개 지방자치단체",
    institution: "공공기관",
    institutionType: "지자체",
    description: "유출·오남용 및 안전조치 조사. 접근권한·접속기록·인증 관리 미흡. 과태료·시정조치",
    itemIds: [14,15,17,18,19],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552641",
  },
  {
    id: "historic-2022-13",
    date: "2022-09-14",
    title: "개인정보보호 법규 위반 5개 사업자",
    targets: "개인정보보호 법규 위반 5개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반에 따른 유출. 접근통제·로그·인증·웹 취약점 미흡. 과징금·과태료·시정조치",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS074&mCode=C020010000&nttId=8223",
  },
  {
    id: "historic-2022-14",
    date: "2022-09-28",
    title: "개인정보보호 법규 위반 8개 사업자",
    targets: "개인정보보호 법규 위반 8개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 의무 소홀. 접근통제·접속기록·인증·웹 보안 미흡. 과태료 3,120만 원 등",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552649",
  },
  {
    id: "historic-2022-15",
    date: "2022-09-28",
    title: "개인정보보호 법규 위반 2개 사업자",
    targets: "개인정보보호 법규 위반 2개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반으로 유출. 접근통제·접속기록·인증·웹 보호 미흡. 과징금 8,297만 원·과태료 360만 원",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552650",
  },
  {
    id: "historic-2022-16",
    date: "2022-11-16",
    title: "개인정보보호 법규 위반 10개 사업자",
    targets: "개인정보보호 법규 위반 10개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "유출·침해신고. 접근통제·접속기록·인증·웹 취약점 등 안전조치 미흡",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS074&mCode=C020010000&nttId=8325",
  },
  {
    id: "historic-2022-17",
    date: "2022-11-16",
    title: "개인정보보호 법규 위반 4개 사업자",
    targets: "개인정보보호 법규 위반 4개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "해킹·유출에 대한 안전조치 의무 위반. 과징금·과태료·시정조치",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552672",
  },
  {
    id: "historic-2022-18",
    date: "2022-11-30",
    title: "개인정보보호 법규 위반 9개 사업자",
    targets: "개인정보보호 법규 위반 9개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치·파기·유출 신고·통지 위반. 총 5,160만 원 과태료",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156551634",
  },
  {
    id: "historic-2022-19",
    date: "2022-11-30",
    title: "통신사·판매점·대리점 11개 사업자",
    targets: "통신사·판매점·대리점 11개 사업자",
    institution: "민간기업",
    institutionType: "민간·통신",
    description: "개인정보파일 비암호화, 수탁자·대리점 안전조치 및 관리·감독 미흡. 과태료 4,100만 원",
    itemIds: [3,19],
    laws: "보호법 제26·29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156552678",
  },
  {
    id: "historic-2022-20",
    date: "2022-12-14",
    title: "개인정보보호 법규 위반 5개 사업자",
    targets: "개인정보보호 법규 위반 5개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치·유출 신고·통지 위반. 과징금 413만 원·과태료 2,280만 원",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156551635",
  },
  {
    id: "historic-2023-01",
    date: "2023-01-11",
    title: "개인정보보호 법규 위반 2개 사업자",
    targets: "개인정보보호 법규 위반 2개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "언론·민원·유출신고 조사. 접근통제·접속기록·인증·웹 보안 미흡",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156551617",
  },
  {
    id: "historic-2023-02",
    date: "2023-02-08",
    title: "개인정보보호 법규 위반 4개 사업자",
    targets: "개인정보보호 법규 위반 4개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "파기·안전조치 위반. 접근통제·접속기록·인증·웹 보호 미흡",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156551637",
  },
  {
    id: "historic-2023-03",
    date: "2023-03-08",
    title: "개인정보보호 법규 위반 4개 사업자",
    targets: "개인정보보호 법규 위반 4개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반에 따른 유출. 과징금·과태료·시정조치",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156556383",
  },
  {
    id: "historic-2023-04",
    date: "2023-03-08",
    title: "한국도로공사서비스 등 12개 공공기관",
    targets: "한국도로공사서비스 등 12개 공공기관",
    institution: "공공기관",
    institutionType: "공공",
    description: "최소·차등 접근권한, 권한 변경·말소, 접속기록 관리 미흡. 과태료·시정조치",
    itemIds: [14,15,17,18,19],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156556371",
  },
  {
    id: "historic-2023-05",
    date: "2023-03-22",
    title: "개인정보보호 법규 위반 6개 사업자",
    targets: "개인정보보호 법규 위반 6개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 소홀로 유출. 접근통제·로그·인증·웹 취약점 미흡",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156558535",
  },
  {
    id: "historic-2023-06",
    date: "2023-04-12",
    title: "한국방송공사 등 8개 공공기관",
    targets: "한국방송공사 등 8개 공공기관",
    institution: "공공기관",
    institutionType: "공공",
    description: "개인정보 보호 소홀·안전조치 위반. 과태료 2,680만 원",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156562303",
  },
  {
    id: "historic-2023-07",
    date: "2023-04-12",
    title: "밀리의서재",
    targets: "밀리의서재",
    institution: "민간기업",
    institutionType: "민간·콘텐츠",
    description: "해킹으로 유출, 안전조치·법정대리인 동의 의무 위반. 과징금 6억 8,496만 원·과태료 2,040만 원",
    itemIds: [6,8,14,19,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156562339",
  },
  {
    id: "historic-2023-08",
    date: "2023-04-26",
    title: "개인정보보호법 위반 4개 사업자",
    targets: "개인정보보호법 위반 4개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전성 확보조치 의무 위반 등. 총 6,135만 원 과징금·과태료",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156564753",
  },
  {
    id: "historic-2023-09",
    date: "2023-05-10",
    title: "서울대병원·국토부·서울교통공사 등 14개 공공기관",
    targets: "서울대병원·국토부·서울교통공사 등 14개 공공기관",
    institution: "공공기관",
    institutionType: "공공·의료",
    description: "해킹·시스템 오류·업무과실, 과도한 접근권한·권한 미말소. 과징금·과태료·개선권고",
    itemIds: [8,14,15,17,18,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156568891",
  },
  {
    id: "historic-2023-10",
    date: "2023-05-24",
    title: "개인정보보호법 위반 11개 사업자",
    targets: "개인정보보호법 위반 11개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반 등. 과징금 5,162만 원·과태료 5,100만 원",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156571277",
  },
  {
    id: "historic-2023-11",
    date: "2023-06-14",
    title: "개인정보보호법 위반 5개 사업자",
    targets: "개인정보보호법 위반 5개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반 등. 과징금 4억 2,615만 원·과태료",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156575018",
  },
  {
    id: "historic-2023-12",
    date: "2023-06-14",
    title: "개인정보보호법 위반 3개 사업자",
    targets: "개인정보보호법 위반 3개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "안전조치 위반 등. 과징금 12억 3,330만 원·과태료",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156575019",
  },
  {
    id: "historic-2023-13",
    date: "2023-06-28",
    title: "LG헬로비전",
    targets: "LG헬로비전",
    institution: "민간기업",
    institutionType: "민간·통신",
    description: "개인정보 유출, 접근통제·로그·인증·웹·서버 관리 미흡. 과징금 11억 3,179만 원·과태료 1,740만 원",
    itemIds: [6,8,10,14,15,19,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156577524",
  },
  {
    id: "historic-2023-14",
    date: "2023-06-28",
    title: "삼성전자·타오월드",
    targets: "삼성전자·타오월드",
    institution: "민간기업",
    institutionType: "민간",
    description: "해킹·개인정보 유출, 접근통제·로그·인증·웹 보호 미흡. 과징금 8억 8,612만 원 등",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156577525",
  },
  {
    id: "historic-2023-15",
    date: "2023-07-12",
    title: "BSC·SK 계열사/수펙스·인크루트",
    targets: "BSC·SK 계열사/수펙스·인크루트",
    institution: "민간기업",
    institutionType: "민간·채용",
    description: "수탁자 관리자페이지 접근통제, 크리덴셜 스터핑 차단·추가인증 미흡, 위탁관리 소홀. 과징금·과태료·시정명령",
    itemIds: [3,6,8,19,25],
    laws: "보호법 제26·29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156580154",
  },
  {
    id: "historic-2023-16",
    date: "2023-07-12",
    title: "LG유플러스 유출사고",
    targets: "LG유플러스 유출사고",
    institution: "민간기업",
    institutionType: "민간·통신",
    description: "노후 OS·DBMS·웹/WAS, 보안장비 미설치·정책 미적용, 웹셸 방치, 접근권한·접속기록 부실. 과징금 68억 원·과태료 2,700만 원·시정명령",
    itemIds: [6,8,10,11,14,15,23,25,26],
    laws: "보호법 제29조·구 정보통신망법 제28조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156580155",
  },
  {
    id: "historic-2023-17",
    date: "2023-07-27",
    title: "경기도교육청 등 개인정보보호 법규 위반 14개 공공기관",
    targets: "경기도교육청 등 개인정보보호 법규 위반 14개 공공기관",
    institution: "공공기관",
    institutionType: "공공",
    description: "성적·주민번호 유출, 접근통제·권한·로그·인증·웹 보안 미흡. 과징금·과태료·시정조치",
    itemIds: [6,14,15,17,18,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156582642",
  },
  {
    id: "historic-2023-18",
    date: "2023-07-27",
    title: "카페24·NHN커머스 등 쇼핑몰솔루션 4개사",
    targets: "카페24·NHN커머스 등 쇼핑몰솔루션 4개사",
    institution: "민간기업",
    institutionType: "민간·수탁",
    description: "140만여 쇼핑몰 대상 솔루션 안전조치·위탁관리 미흡. 과태료·시정명령",
    itemIds: [3,6,8,14,19,25],
    laws: "보호법 제26·29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156582641",
  },
  {
    id: "historic-2023-19",
    date: "2023-07-27",
    title: "환자정보 유출 17개 종합병원",
    targets: "환자정보 유출 17개 종합병원",
    institution: "민간기업",
    institutionType: "의료",
    description: "직원·제약사 직원의 무단접근, 촬영·다운로드·이메일·USB 반출, 접근권한·로그 점검 미흡. 과징금·과태료·시정명령",
    itemIds: [14,15,17,18,22],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156582640",
  },
  {
    id: "historic-2023-20",
    date: "2023-10-12",
    title: "경북대 등 6개 공공기관",
    targets: "경북대 등 6개 공공기관",
    institution: "공공기관",
    institutionType: "공공·교육",
    description: "동일 해커 공격으로 81만여 건 유출. 웹·서버 취약점과 보안패치·침입방지 미흡. 과징금·과태료",
    itemIds: [8,11,23,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156594019",
  },
  {
    id: "historic-2023-21",
    date: "2023-10-12",
    title: "슈나이더일렉트릭코리아·신일전자",
    targets: "슈나이더일렉트릭코리아·신일전자",
    institution: "민간기업",
    institutionType: "민간",
    description: "방화벽·침입탐지 미흡, SQL 주입 입력값 검증 및 취급자 비밀번호 관리 소홀. KB국민카드는 안전조치 직접 관련성이 없어 이 후보에서 제외",
    itemIds: [6,8,19,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156594021",
  },
  {
    id: "historic-2023-22",
    date: "2023-10-26",
    title: "PayPal",
    targets: "PayPal",
    institution: "민간기업",
    institutionType: "해외 민간·결제",
    description: "크리덴셜 스터핑 등 복수 유출사고, 이상 로그인 차단·추가 인증·웹 접근통제 미흡. 과징금 9억 600만 원·과태료 1,620만 원",
    itemIds: [8,19,20,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156596274",
  },
  {
    id: "historic-2023-23",
    date: "2023-10-26",
    title: "안전조치 의무 위반 3개 사업자",
    targets: "안전조치 의무 위반 3개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "웹셸 공격 예방을 위한 주기적 취약점·보안패치 미흡. 과징금·과태료·시정조치",
    itemIds: [8,11,23,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156596276",
  },
  {
    id: "historic-2023-24",
    date: "2023-11-09",
    title: "한림성심대·육군학생군사학교·해운대교육지원청",
    targets: "한림성심대·육군학생군사학교·해운대교육지원청",
    institution: "공공기관",
    institutionType: "공공·교육",
    description: "주민등록번호 유출, 접근통제·접속기록·권한·웹 보안 미흡. 과징금·과태료·시정조치",
    itemIds: [6,14,15,17,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156598809",
  },
  {
    id: "historic-2023-25",
    date: "2023-11-23",
    title: "백패커",
    targets: "백패커",
    institution: "민간기업",
    institutionType: "민간·플랫폼",
    description: "해킹·개인정보 유출, 접근통제·접속기록·인증·웹 취약점 관리 미흡. 총 2억 2,789만 원 제재",
    itemIds: [6,8,14,19,25],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156601215",
  },
  {
    id: "historic-2023-26",
    date: "2023-11-23",
    title: "엠비아이솔루션·다배송",
    targets: "엠비아이솔루션·다배송",
    institution: "민간기업",
    institutionType: "민간·수탁",
    description: "DB 관리자 비밀번호·접근통제·접속기록 관리, 로그인 검증 미흡. 시정명령·결과공표",
    itemIds: [6,10,12,14,19],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156601214",
  },
  {
    id: "historic-2023-27",
    date: "2023-12-14",
    title: "안전조치 의무 위반 2개 사업자",
    targets: "안전조치 의무 위반 2개 사업자",
    institution: "민간기업",
    institutionType: "민간",
    description: "SQL 주입·웹셸 등 공격, 접근통제·인증·웹 취약점·서버 보안 미흡. 과징금·과태료·시정조치",
    itemIds: [6,8,19,25,26],
    laws: "보호법 제29조",
    source: "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156605140",
  },
];

const toCaseRecord = (input: HistoricalCaseInput): CaseRecord => {
  const dispositions: string[] = dispositionLabels.filter((label) => input.description.includes(label));
  if (input.description.includes("시정조치") && !dispositions.includes("시정명령") && !dispositions.includes("시정권고")) {
    dispositions.push("시정조치");
  }
  if (input.description.includes("공표") && !dispositions.some((label) => label.includes("공표"))) {
    dispositions.push("공표");
  }

  const itemNumbers = input.itemIds.join("·");
  const topics = Array.from(new Set(input.itemIds.map((id) => topicByItem[id]).filter(Boolean)));
  const learning = Array.from(new Set(input.itemIds.map((id) => learningByItem[id]).filter(Boolean)));

  return {
    id: input.id,
    date: input.date,
    title: input.title,
    targets: input.targets,
    institution: input.institution,
    dispositions,
    dispositionSummary: input.description,
    itemIds: input.itemIds,
    topics,
    problems: [input.description],
    summary: input.description,
    relation: `공식 보도자료에서 확인된 안전조치 위반사실을 현재 자가점검 도구의 ${itemNumbers}번 점검항목과 직접 대조한 사례입니다.`,
    learning,
    laws: [input.laws],
    source: input.source,
    sourceType: "개인정보위 보도자료",
    historicalNote: `${input.date.slice(0, 4)}년 처분 당시 적용 법령과 고시를 기준으로 정리했습니다. 현재 자가점검 항목은 현행 보호조치와의 대응 관계를 보여주며, 과거 사건에 현행 조문을 소급 적용한 것이 아닙니다. 기관 유형: ${input.institutionType}.`,
  };
};

export const historicalCaseRecords: CaseRecord[] = historicalCaseInputs.map(toCaseRecord);
